### PR TITLE
Update de locale

### LINKED ISSUE #43: Takeout folders are localized according to accounts main language
## problem
If an account doesn't have english as its main language, folders and some files are named differently (localized). 
This results into no parsed folders due to [_match_handler](https://github.com/seanbreckenridge/google_takeout_parser/blob/368017199f822196f78a3e70f7b27584066b8796/google_takeout_parser/path_dispatch.py#L223) misses.

## possible solution
I think it would be beneficial to add default handler maps like defined [here (DEFAULT_HANDLER_MAP)](https://github.com/seanbreckenridge/google_takeout_parser/blob/368017199f822196f78a3e70f7b27584066b8796/google_takeout_parser/path_dispatch.py#L95) for other languages.  
An user could select a HandlerMap via command line argument.

If you approve this idea I could work on a pull request for adding a german localization as well as a command line argument for selecting a handler map.

If there's already an option to achieve this please fill me in :)

### PR DESCRIPTION
**Pull request by parthux1**
As mentioned  I updated folder names according to my recent export.

Ready to merge which could close #43.

-----

```
[W 240103 23:15:04 path_dispatch:356] time data '01.09.2022, 21:08:12' does not match format '%b %d, %Y, %I:%M:%S %p'
```
Is logged (a lot) when parsing `YouTube( und YouTube Music)?/Verlauf/.*?.html` using [this function](https://github.com/seanbreckenridge/google_takeout_parser/blob/6561a6a4c89fc75766e83f624fb1a50fc4700b91/google_takeout_parser/parse_html/activity.py#L335).

Because you're reading meta information via OS-calls I don't think this has anything to do with locales. I'd assume there's an incompatibility with Ubuntu 23.10, all locales on en_US.

### CODE REVIEW

**Comment by parthux1** [comment]
Ah I guess I have to update some tests

**Comment by parthux1** [comment]
@seanbreckenridge I don't have a local windows instance for testing purposes. You might need to fix the last pipeline. 

https://github.com/seanbreckenridge/google_takeout_parser/pull/59/commits/985dc0916a36fbfa1c9aa2e671ce2b30e7ddfe11 contains all relevant changes on the tests.

**Comment by seanbreckenridge** [comment]
yeah, was just looking at it

its probably fine that it doesnt work exactly,the locale paths there are only used to detect which locale to use

**Comment by seanbreckenridge** [comment]
Thanks again! Glad we were able to figure this out, should be much easier to go from 2 locales to 3 in the future :+1: 

will make a release for this soon

**Pull request merged**
